### ISSUE TITLE
Don't work under linux

### ISSUE THREAD

**Issue by lf-araujo** [vaemoi/SublimeLinter-contrib-tailor#1]
Thanks for the package.

It does not work under Linux, however.

```
which tailor
/usr/bin/tailor
```

Sublime Text 3, Sublime Linter in Archlinux. What else can I post here for debugging?

**Comment by lf-araujo** [comment]
Can confirm this is also the case under Ubuntu 16.10.

**Comment by brwnrclse** [comment]
Hello,

The linter [tailor] isn't provided by this package and maintained by me so I'm going to close this. I've also updated the README for this repo with a link to the installation instructions for tailer so hopefully that issue is cleared up in the future :+1:
